<#
.SYNOPSIS
    DecompileDll.ps1 の Pester 5 向け統合テスト。

.DESCRIPTION
    既存の Tests/Integration/Test-DecompileDll.ps1 のテストロジックを
    Describe/Context/It 構造へ分解したテストスクリプトです。

    前提条件:
    - DecompileDLL/Script/DecompileDll.ps1 が存在すること
    - powershell-yaml モジュールがインストール済みであること
    - Windows 環境であること（対象スクリプト仕様）

        実行例:
            Invoke-Pester -Path .\Tests\Integration\DecompileDll.Tests.ps1

    任意の環境変数:
      DECOMPILEDLL_TEST_TIMEOUT=180
      DECOMPILEDLL_KEEP_ARTIFACTS=1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Describe 'DecompileDll integration tests' {
    BeforeAll {
        <#
        .SYNOPSIS
            値が真偽として true と判定されるとき $true、それ以外は $false を返す。
        #>
        function script:Test-Truthy {
            param([string]$Value)
            if ([string]::IsNullOrWhiteSpace($Value)) { return $false }
            return $Value -match '^(?i:1|true|yes|on)$'
        }

        <#
        .SYNOPSIS
            ILSpyCmd のスタブ用 cmd シムファイルを作成して返す。
        #>
        function script:New-IlspyShim {
            param([Parameter(Mandatory = $true)][string]$ShimDirectory)

            New-Item -Path $ShimDirectory -ItemType Directory -Force | Out-Null
            $shimPath = Join-Path $ShimDirectory 'ILSpyCmd.cmd'
            $content = @'
@echo off
setlocal

if /I "%ILSPY_SHIM_MODE%"=="fail" (
    exit /b 1
)

set "outDir="

:parse
if "%~1"=="" goto create
if /I "%~1"=="-o" (
    set "outDir=%~2"
    shift
)
shift
goto parse

:create
if not "%outDir%"=="" (
    if not exist "%outDir%" mkdir "%outDir%" >nul 2>&1
    echo // generated by ILSpyCmd shim>"%outDir%\Decompiled.cs"
)

exit /b 0
'@

            Set-Content -Path $shimPath -Value $content -Encoding Ascii -NoNewline
            return $shimPath
        }

        <#
        .SYNOPSIS
            テスト用の Old/New DLL ペアをファイルシステム上に作成する。
        #>
        function script:New-TestDllPair {
            param(
                [Parameter(Mandatory = $true)][string]$OldDir,
                [Parameter(Mandatory = $true)][string]$NewDir,
                [Parameter(Mandatory = $true)][string]$BaseName
            )

            New-Item -Path $OldDir -ItemType Directory -Force | Out-Null
            New-Item -Path $NewDir -ItemType Directory -Force | Out-Null
            Set-Content -Path (Join-Path $OldDir ("{0}.dll" -f $BaseName)) -Value 'old-dummy' -Encoding UTF8
            Set-Content -Path (Join-Path $NewDir ("{0}.dll" -f $BaseName)) -Value 'new-dummy' -Encoding UTF8
        }

        <#
        .SYNOPSIS
            テスト用の YAML 設定ファイルを指定パスへ書き込む。
        #>
        function script:New-TestYaml {
            param(
                [Parameter(Mandatory = $true)][string]$YamlPath,
                [Parameter(Mandatory = $true)][string]$LogRelativePath,
                [Parameter(Mandatory = $true)][string]$FolderOld,
                [Parameter(Mandatory = $true)][string]$FolderNew,
                [Parameter(Mandatory = $true)][string]$FolderDecompile,
                [Parameter(Mandatory = $true)][string]$WinMergeStubDirectory,
                [switch]$InvalidForGeneralError
            )

            $yaml = @"
Project: Test(DecompileDll)
Version: 1.0.0

LOG:
  Path: $LogRelativePath
  FILENAME: DecompileDll
  EXTENSION: .log

Folders:
  Decompile: $FolderDecompile
  Old: $FolderOld
  New: $FolderNew

OSDetection:
  Win11MinBuild: 22000
  Win10MinBuild: 10240

ExitCodes:
  Success: 0
  GeneralError: 1
  UserCancelled: 2
  OSNotSupported: 3
  FileNotFound: 4
  DecompileFailed: 5

Colors:
  Info: Cyan
  Success: Green
  Warning: Yellow
  Error: Red

Retry:
  MaxAttempts: 2
  DelaySeconds: 1
  TimeoutSeconds: 15
"@

            if (-not $InvalidForGeneralError) {
                $yaml += @"

InstWinMerge:
  Win10: $WinMergeStubDirectory
  Win11: $WinMergeStubDirectory
"@
            }

            Set-Content -Path $YamlPath -Value $yaml -Encoding UTF8
        }

        <#
        .SYNOPSIS
            DecompileDll.ps1 を子プロセスで実行し、終了コードと標準出力を返す。
        #>
        function script:Invoke-DecompileScript {
            param(
                [Parameter(Mandatory = $true)][string]$ScriptPath,
                [Parameter(Mandatory = $true)][string]$WorkingDirectory,
                [Parameter(Mandatory = $true)][string[]]$Arguments,
                [Parameter(Mandatory = $true)][string]$StdoutPath,
                [Parameter(Mandatory = $true)][string]$StderrPath,
                [Parameter(Mandatory = $true)][int]$TimeoutSeconds,
                [ValidateSet('success', 'fail')][string]$IlspyMode
            )

            $env:ILSPY_SHIM_MODE = $IlspyMode
            $argList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $ScriptPath) + $Arguments

            $process = Start-Process -FilePath 'pwsh' `
                -ArgumentList $argList `
                -WorkingDirectory $WorkingDirectory `
                -PassThru `
                -RedirectStandardOutput $StdoutPath `
                -RedirectStandardError $StderrPath

            $timedOut = -not $process.WaitForExit($TimeoutSeconds * 1000)
            if ($timedOut) {
                try { Stop-Process -Id $process.Id -Force -ErrorAction Stop } catch { Write-Debug "Stop-Process skipped: $_" }
                return [PSCustomObject]@{
                    TimedOut = $true
                    ExitCode = $null
                    Stdout = if (Test-Path $StdoutPath) { Get-Content -Path $StdoutPath -Raw -Encoding UTF8 } else { '' }
                    Stderr = if (Test-Path $StderrPath) { Get-Content -Path $StderrPath -Raw -Encoding UTF8 } else { '' }
                    CommandText = 'pwsh ' + (($argList | ForEach-Object { if ($_ -match '\s') { '"{0}"' -f $_ } else { $_ } }) -join ' ')
                }
            }

            return [PSCustomObject]@{
                TimedOut = $false
                ExitCode = $process.ExitCode
                Stdout = if (Test-Path $StdoutPath) { Get-Content -Path $StdoutPath -Raw -Encoding UTF8 } else { '' }
                Stderr = if (Test-Path $StderrPath) { Get-Content -Path $StderrPath -Raw -Encoding UTF8 } else { '' }
                CommandText = 'pwsh ' + (($argList | ForEach-Object { if ($_ -match '\s') { '"{0}"' -f $_ } else { $_ } }) -join ' ')
            }
        }

        <#
        .SYNOPSIS
            指定フォルダー内で条件に一致するファイル数を返す。
        #>
        function script:Get-ArtifactFileCount {
            param(
                [Parameter(Mandatory = $true)][string]$Path,
                [Parameter(Mandatory = $true)][string]$Filter
            )
            if (-not (Test-Path $Path)) { return 0 }
            return @(Get-ChildItem -Path $Path -Filter $Filter -File -ErrorAction SilentlyContinue).Count
        }

        <#
        .SYNOPSIS
            テストケースで生成したアーティファクトをクリーンアップリストに登録する。
        #>
        function script:Register-CaseArtifact {
            param(
                [Parameter(Mandatory = $true)][pscustomobject]$SetupInfo,
                [Parameter(Mandatory = $true)][string]$StdoutPath,
                [Parameter(Mandatory = $true)][string]$StderrPath
            )

            $script:CaseArtifacts.Add([PSCustomObject]@{
                YamlPath = Join-Path $script:YamlDir $SetupInfo.EnvYaml
                OldDir = Join-Path $script:DllRoot $SetupInfo.OldFolder
                NewDir = Join-Path $script:DllRoot $SetupInfo.NewFolder
                DecompiledDir = Join-Path $script:DllRoot $SetupInfo.DecompileFolder
                StdoutPath = $StdoutPath
                StderrPath = $StderrPath
            }) | Out-Null
        }

        <#
        .SYNOPSIS
            登録済みのテストアーティファクトをすべて削除する。
        #>
        function script:Clear-CaseArtifact {
            foreach ($artifact in @($script:CaseArtifacts)) {
                Remove-Item -Path $artifact.YamlPath -Force -ErrorAction SilentlyContinue
                Remove-Item -Path $artifact.OldDir -Recurse -Force -ErrorAction SilentlyContinue
                Remove-Item -Path $artifact.NewDir -Recurse -Force -ErrorAction SilentlyContinue
                Remove-Item -Path $artifact.DecompiledDir -Recurse -Force -ErrorAction SilentlyContinue
                Remove-Item -Path $artifact.StdoutPath -Force -ErrorAction SilentlyContinue
                Remove-Item -Path $artifact.StderrPath -Force -ErrorAction SilentlyContinue
            }
            $script:CaseArtifacts.Clear()
        }

        <#
        .SYNOPSIS
            テストケース定義オブジェクトを生成して返す。
        #>
        function script:New-CaseDefinition {
            param(
                [Parameter(Mandatory = $true)][string]$Name,
                [Parameter(Mandatory = $true)][string]$Description,
                [Parameter(Mandatory = $true)][int]$ExpectedExitCode,
                [Parameter(Mandatory = $true)][ValidateSet('success', 'fail')][string]$IlspyMode,
                [Parameter(Mandatory = $true)][string[]]$Args,
                [Parameter(Mandatory = $true)][bool]$ExpectLog,
                [Parameter(Mandatory = $true)][bool]$ExpectErrorReport,
                [Parameter(Mandatory = $true)][bool]$VerifyWhatIf,
                [Parameter(Mandatory = $true)][scriptblock]$Setup
            )
            return [PSCustomObject]@{
                Name = $Name
                Description = $Description
                ExpectedExitCode = $ExpectedExitCode
                IlspyMode = $IlspyMode
                Args = $Args
                ExpectLog = $ExpectLog
                ExpectErrorReport = $ExpectErrorReport
                VerifyWhatIf = $VerifyWhatIf
                Setup = $Setup
            }
        }

        <#
        .SYNOPSIS
            テストケースのセットアップ情報オブジェクトを生成して返す。
        #>
        function script:New-SetupInfo {
            param(
                [Parameter(Mandatory = $true)][string]$Suffix,
                [Parameter(Mandatory = $true)][string]$LogRelativePath
            )

            $oldFolder = "it_old_${Suffix}_$($script:RunId)"
            $newFolder = "it_new_${Suffix}_$($script:RunId)"
            $decompileFolder = "it_decompiled_${Suffix}_$($script:RunId)"
            $yamlName = "Test-Decompile-$Suffix-$($script:RunId).yaml"

            return [PSCustomObject]@{
                EnvYaml = $yamlName
                YamlPath = Join-Path $script:YamlDir $yamlName
                LogPath = $LogRelativePath
                OldFolder = $oldFolder
                NewFolder = $newFolder
                DecompileFolder = $decompileFolder
                OldDir = Join-Path $script:DllRoot $oldFolder
                NewDir = Join-Path $script:DllRoot $newFolder
                DecompiledDir = Join-Path $script:DllRoot $decompileFolder
                Tag = $Suffix
            }
        }

        <#
        .SYNOPSIS
            テストケースを実行し、検証結果オブジェクトを返す。
        #>
        function script:Invoke-DecompileCase {
            param([Parameter(Mandatory = $true)][pscustomobject]$Case)

            if ($script:PrereqSkip) {
                Set-ItResult -Skipped -Because $script:PrereqSkipReason
                return
            }

            $setupInfo = & $Case.Setup $script:DecompileRoot $script:YamlDir $script:DllRoot $script:SuiteRootRelative
            $scriptArgs = @('-EnvYaml', $setupInfo.EnvYaml) + $Case.Args
            $logAbs = Join-Path $script:DecompileRoot ($setupInfo.LogPath -replace '/', '\\')
            $stdoutPath = Join-Path $script:TempWork ("stdout_{0}_{1}.txt" -f $setupInfo.Tag, ([guid]::NewGuid().ToString('N')))
            $stderrPath = Join-Path $script:TempWork ("stderr_{0}_{1}.txt" -f $setupInfo.Tag, ([guid]::NewGuid().ToString('N')))

            Register-CaseArtifact -SetupInfo $setupInfo -StdoutPath $stdoutPath -StderrPath $stderrPath

            $beforeLogCount = Get-ArtifactFileCount -Path $logAbs -Filter 'DecompileDll_*.log'
            $beforeErrorCount = Get-ArtifactFileCount -Path $logAbs -Filter 'DecompileErrors_*.txt'

            $invokeResult = Invoke-DecompileScript -ScriptPath $script:TargetScript -WorkingDirectory $script:DecompileRoot -Arguments $scriptArgs -StdoutPath $stdoutPath -StderrPath $stderrPath -TimeoutSeconds $script:TimeoutSeconds -IlspyMode $Case.IlspyMode

            $afterLogCount = Get-ArtifactFileCount -Path $logAbs -Filter 'DecompileDll_*.log'
            $afterErrorCount = Get-ArtifactFileCount -Path $logAbs -Filter 'DecompileErrors_*.txt'

            $newLogCount = $afterLogCount - $beforeLogCount
            $newErrorCount = $afterErrorCount - $beforeErrorCount

            $logCheck = if ($Case.ExpectLog) { $newLogCount -ge 1 } else { $true }
            $errorCheck = if ($Case.ExpectErrorReport) { $newErrorCount -ge 1 } else { $newErrorCount -eq 0 }
            $whatIfCheck = $true

            if ($Case.VerifyWhatIf) {
                $combinedOutput = "{0}`n{1}" -f $invokeResult.Stdout, $invokeResult.Stderr
                $whatIfCheck = $combinedOutput -match 'What if|WhatIf|逆コンパイルを実行'
            }

            return [PSCustomObject]@{
                TimedOut = $invokeResult.TimedOut
                ExitCode = $invokeResult.ExitCode
                LogCheck = $logCheck
                ErrorReportCheck = $errorCheck
                WhatIfCheck = $whatIfCheck
            }
        }

        $script:RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
        $script:DecompileRoot = Join-Path $script:RepoRoot 'DecompileDLL'
        $script:TargetScript = Join-Path $script:DecompileRoot 'Script\DecompileDll.ps1'
        $script:YamlDir = Join-Path $script:DecompileRoot 'YAML'
        $script:DllRoot = Join-Path $script:DecompileRoot 'Dlls'
        $script:RunId = Get-Date -Format 'yyyyMMdd-HHmmss'
        $script:SuiteRootRelative = "LOG/Test-DecompileDll/Pester-$($script:RunId)"
        $script:SuiteRootAbsolute = Join-Path $script:DecompileRoot ($script:SuiteRootRelative -replace '/', '\\')
        $script:TempWork = Join-Path $script:SuiteRootAbsolute 'runner-temp'
        $script:ShimDir = Join-Path $script:TempWork 'shim'
        $script:WinMergeStubDir = Join-Path $script:TempWork 'winmerge-stub'
        $script:OriginalPath = $env:PATH
        $script:CaseArtifacts = [System.Collections.Generic.List[object]]::new()
        $script:KeepArtifacts = Test-Truthy -Value $env:DECOMPILEDLL_KEEP_ARTIFACTS
        $script:TimeoutSeconds = 180
        $script:PrereqSkip = $false
        $script:PrereqSkipReason = ''

        if (-not [string]::IsNullOrWhiteSpace($env:DECOMPILEDLL_TEST_TIMEOUT)) {
            $tmpTimeout = 0
            if ([int]::TryParse($env:DECOMPILEDLL_TEST_TIMEOUT, [ref]$tmpTimeout) -and $tmpTimeout -gt 0) {
                $script:TimeoutSeconds = $tmpTimeout
            }
        }

        if (-not (Test-Path $script:TargetScript)) {
            $script:PrereqSkip = $true
            $script:PrereqSkipReason = "対象スクリプトが見つかりません: $script:TargetScript"
            return
        }

        $moduleAvailable = [bool](Get-Module -ListAvailable -Name 'powershell-yaml')
        if (-not $moduleAvailable) {
            $script:PrereqSkip = $true
            $script:PrereqSkipReason = 'powershell-yaml モジュールが見つからないためスキップ'
            return
        }

        New-Item -Path $script:SuiteRootAbsolute -ItemType Directory -Force | Out-Null
        New-Item -Path $script:TempWork -ItemType Directory -Force | Out-Null
        New-Item -Path $script:WinMergeStubDir -ItemType Directory -Force | Out-Null
        Copy-Item -Path (Join-Path $env:WINDIR 'System32\where.exe') -Destination (Join-Path $script:WinMergeStubDir 'WinMergeU.exe') -Force

        $null = New-IlspyShim -ShimDirectory $script:ShimDir
        $env:PATH = "$script:ShimDir;$env:PATH"

        $script:Cases = @{
            'Basic-Sequential' = New-CaseDefinition -Name 'Basic-Sequential' -Description '順次処理・CleanOutput・Force・NoKeyWait で正常終了' -ExpectedExitCode 0 -IlspyMode 'success' -Args @('-CleanOutput', '-Force', '-NoKeyWait') -ExpectLog $true -ExpectErrorReport $false -VerifyWhatIf $false -Setup {
                param($decompileRoot, $yamlDir, $dllRoot, $suiteRootRelative)
                $info = New-SetupInfo -Suffix 'basic' -LogRelativePath "$suiteRootRelative/basic"
                New-TestYaml -YamlPath $info.YamlPath -LogRelativePath $info.LogPath -FolderOld $info.OldFolder -FolderNew $info.NewFolder -FolderDecompile $info.DecompileFolder -WinMergeStubDirectory $script:WinMergeStubDir
                New-TestDllPair -OldDir $info.OldDir -NewDir $info.NewDir -BaseName 'SampleLib'
                return $info
            }
            'Parallel-Throttle4' = New-CaseDefinition -Name 'Parallel-Throttle4' -Description '並列処理 -Parallel -ThrottleLimit 4 で正常終了' -ExpectedExitCode 0 -IlspyMode 'success' -Args @('-Parallel', '-ThrottleLimit', '4', '-CleanOutput', '-Force', '-NoKeyWait') -ExpectLog $true -ExpectErrorReport $false -VerifyWhatIf $false -Setup {
                param($decompileRoot, $yamlDir, $dllRoot, $suiteRootRelative)
                $info = New-SetupInfo -Suffix 'parallel' -LogRelativePath "$suiteRootRelative/parallel"
                New-TestYaml -YamlPath $info.YamlPath -LogRelativePath $info.LogPath -FolderOld $info.OldFolder -FolderNew $info.NewFolder -FolderDecompile $info.DecompileFolder -WinMergeStubDirectory $script:WinMergeStubDir
                New-TestDllPair -OldDir $info.OldDir -NewDir $info.NewDir -BaseName 'ParallelLib01'
                New-TestDllPair -OldDir $info.OldDir -NewDir $info.NewDir -BaseName 'ParallelLib02'
                return $info
            }
            'DiffTool-VSCode' = New-CaseDefinition -Name 'DiffTool-VSCode' -Description '-DiffTool VSCode 指定で異常終了しないこと' -ExpectedExitCode 0 -IlspyMode 'success' -Args @('-DiffTool', 'VSCode', '-NoKeyWait', '-Force') -ExpectLog $true -ExpectErrorReport $false -VerifyWhatIf $false -Setup {
                param($decompileRoot, $yamlDir, $dllRoot, $suiteRootRelative)
                $info = New-SetupInfo -Suffix 'vscode' -LogRelativePath "$suiteRootRelative/vscode"
                New-TestYaml -YamlPath $info.YamlPath -LogRelativePath $info.LogPath -FolderOld $info.OldFolder -FolderNew $info.NewFolder -FolderDecompile $info.DecompileFolder -WinMergeStubDirectory $script:WinMergeStubDir
                New-TestDllPair -OldDir $info.OldDir -NewDir $info.NewDir -BaseName 'VSCodeLib'
                return $info
            }
            'DiffTool-Custom' = New-CaseDefinition -Name 'DiffTool-Custom' -Description '-DiffTool Custom 指定で異常終了しないこと' -ExpectedExitCode 0 -IlspyMode 'success' -Args @('-DiffTool', 'Custom', '-NoKeyWait', '-Force') -ExpectLog $true -ExpectErrorReport $false -VerifyWhatIf $false -Setup {
                param($decompileRoot, $yamlDir, $dllRoot, $suiteRootRelative)
                $info = New-SetupInfo -Suffix 'custom' -LogRelativePath "$suiteRootRelative/custom"
                New-TestYaml -YamlPath $info.YamlPath -LogRelativePath $info.LogPath -FolderOld $info.OldFolder -FolderNew $info.NewFolder -FolderDecompile $info.DecompileFolder -WinMergeStubDirectory $script:WinMergeStubDir
                New-TestDllPair -OldDir $info.OldDir -NewDir $info.NewDir -BaseName 'CustomLib'
                return $info
            }
            'WhatIf' = New-CaseDefinition -Name 'WhatIf' -Description 'WhatIf で実処理せず終了コード 0' -ExpectedExitCode 0 -IlspyMode 'success' -Args @('-WhatIf', '-NoKeyWait', '-DiffTool', 'Custom') -ExpectLog $false -ExpectErrorReport $false -VerifyWhatIf $true -Setup {
                param($decompileRoot, $yamlDir, $dllRoot, $suiteRootRelative)
                $info = New-SetupInfo -Suffix 'whatif' -LogRelativePath "$suiteRootRelative/whatif"
                New-TestYaml -YamlPath $info.YamlPath -LogRelativePath $info.LogPath -FolderOld $info.OldFolder -FolderNew $info.NewFolder -FolderDecompile $info.DecompileFolder -WinMergeStubDirectory $script:WinMergeStubDir
                New-TestDllPair -OldDir $info.OldDir -NewDir $info.NewDir -BaseName 'WhatIfLib'
                return $info
            }
            'Error-DecompileFailed' = New-CaseDefinition -Name 'Error-DecompileFailed' -Description 'ILSpyCmd を失敗させて DecompileFailed(5) を検証' -ExpectedExitCode 5 -IlspyMode 'fail' -Args @('-DiffTool', 'Custom', '-NoKeyWait', '-Force') -ExpectLog $true -ExpectErrorReport $true -VerifyWhatIf $false -Setup {
                param($decompileRoot, $yamlDir, $dllRoot, $suiteRootRelative)
                $info = New-SetupInfo -Suffix 'decompilefailed' -LogRelativePath "$suiteRootRelative/decompilefailed"
                New-TestYaml -YamlPath $info.YamlPath -LogRelativePath $info.LogPath -FolderOld $info.OldFolder -FolderNew $info.NewFolder -FolderDecompile $info.DecompileFolder -WinMergeStubDirectory $script:WinMergeStubDir
                New-TestDllPair -OldDir $info.OldDir -NewDir $info.NewDir -BaseName 'FailLib'
                return $info
            }
            'Error-FileNotFound-OldEmpty' = New-CaseDefinition -Name 'Error-FileNotFound-OldEmpty' -Description 'Old DLL フォルダーを空にして FileNotFound(4) を想定（ポップアップがあるため既定スキップ）' -ExpectedExitCode 4 -IlspyMode 'success' -Args @('-NoKeyWait', '-Force') -ExpectLog $true -ExpectErrorReport $false -VerifyWhatIf $false -Setup {
                param($decompileRoot, $yamlDir, $dllRoot, $suiteRootRelative)
                $info = New-SetupInfo -Suffix 'filenotfound' -LogRelativePath "$suiteRootRelative/filenotfound"
                New-TestYaml -YamlPath $info.YamlPath -LogRelativePath $info.LogPath -FolderOld $info.OldFolder -FolderNew $info.NewFolder -FolderDecompile $info.DecompileFolder -WinMergeStubDirectory $script:WinMergeStubDir
                New-Item -Path $info.OldDir -ItemType Directory -Force | Out-Null
                $tmpOldDir = Join-Path $dllRoot 'it_tmp_dummy_old'
                New-TestDllPair -OldDir $tmpOldDir -NewDir $info.NewDir -BaseName 'DummyNew'
                Remove-Item -Path $tmpOldDir -Recurse -Force -ErrorAction SilentlyContinue
                return $info
            }
            'Error-GeneralError-InvalidYaml' = New-CaseDefinition -Name 'Error-GeneralError-InvalidYaml' -Description 'YAML から InstWinMerge を除外して GeneralError(1) を想定（ポップアップがあるため既定スキップ）' -ExpectedExitCode 1 -IlspyMode 'success' -Args @('-NoKeyWait', '-Force') -ExpectLog $true -ExpectErrorReport $false -VerifyWhatIf $false -Setup {
                param($decompileRoot, $yamlDir, $dllRoot, $suiteRootRelative)
                $info = New-SetupInfo -Suffix 'generalerror' -LogRelativePath "$suiteRootRelative/generalerror"
                New-TestYaml -YamlPath $info.YamlPath -LogRelativePath $info.LogPath -FolderOld $info.OldFolder -FolderNew $info.NewFolder -FolderDecompile $info.DecompileFolder -WinMergeStubDirectory $script:WinMergeStubDir -InvalidForGeneralError
                New-TestDllPair -OldDir $info.OldDir -NewDir $info.NewDir -BaseName 'GeneralErrLib'
                return $info
            }
        }
    }

    AfterEach {
        if (-not $script:KeepArtifacts) {
            Clear-CaseArtifact
        }
    }

    AfterAll {
        $env:PATH = $script:OriginalPath
        Remove-Item Env:ILSPY_SHIM_MODE -ErrorAction SilentlyContinue

        if (-not $script:KeepArtifacts) {
            Clear-CaseArtifact
            Remove-Item -Path $script:TempWork -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path $script:SuiteRootAbsolute -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    Context 'Sequential mode' {
        It 'Basic-Sequential' {
            $result = Invoke-DecompileCase -Case $script:Cases['Basic-Sequential']
            $result.TimedOut | Should -BeFalse
            $result.ExitCode | Should -Be $script:Cases['Basic-Sequential'].ExpectedExitCode
            $result.LogCheck | Should -BeTrue
            $result.ErrorReportCheck | Should -BeTrue
            $result.WhatIfCheck | Should -BeTrue
        }
    }

    Context 'Parallel mode' {
        It 'Parallel-Throttle4' {
            $result = Invoke-DecompileCase -Case $script:Cases['Parallel-Throttle4']
            $result.TimedOut | Should -BeFalse
            $result.ExitCode | Should -Be $script:Cases['Parallel-Throttle4'].ExpectedExitCode
            $result.LogCheck | Should -BeTrue
            $result.ErrorReportCheck | Should -BeTrue
            $result.WhatIfCheck | Should -BeTrue
        }
    }

    Context 'DiffTool variants' {
        It 'DiffTool-VSCode' {
            $result = Invoke-DecompileCase -Case $script:Cases['DiffTool-VSCode']
            $result.TimedOut | Should -BeFalse
            $result.ExitCode | Should -Be $script:Cases['DiffTool-VSCode'].ExpectedExitCode
            $result.LogCheck | Should -BeTrue
            $result.ErrorReportCheck | Should -BeTrue
            $result.WhatIfCheck | Should -BeTrue
        }

        It 'DiffTool-Custom' {
            $result = Invoke-DecompileCase -Case $script:Cases['DiffTool-Custom']
            $result.TimedOut | Should -BeFalse
            $result.ExitCode | Should -Be $script:Cases['DiffTool-Custom'].ExpectedExitCode
            $result.LogCheck | Should -BeTrue
            $result.ErrorReportCheck | Should -BeTrue
            $result.WhatIfCheck | Should -BeTrue
        }
    }

    Context 'WhatIf' {
        It 'WhatIf' {
            $result = Invoke-DecompileCase -Case $script:Cases['WhatIf']
            $result.TimedOut | Should -BeFalse
            $result.ExitCode | Should -Be $script:Cases['WhatIf'].ExpectedExitCode
            $result.LogCheck | Should -BeTrue
            $result.ErrorReportCheck | Should -BeTrue
            $result.WhatIfCheck | Should -BeTrue
        }
    }

    Context 'Error conditions' {
        It 'Error-DecompileFailed' {
            $result = Invoke-DecompileCase -Case $script:Cases['Error-DecompileFailed']
            $result.TimedOut | Should -BeFalse
            $result.ExitCode | Should -Be $script:Cases['Error-DecompileFailed'].ExpectedExitCode
            $result.LogCheck | Should -BeTrue
            $result.ErrorReportCheck | Should -BeTrue
            $result.WhatIfCheck | Should -BeTrue
        }

        # Show-ErrorPopup がブロッキングなため、CI向け自動実行ではスキップ
        It 'Error-FileNotFound-OldEmpty' -Skip {
            $result = Invoke-DecompileCase -Case $script:Cases['Error-FileNotFound-OldEmpty']
            $result.TimedOut | Should -BeFalse
            $result.ExitCode | Should -Be $script:Cases['Error-FileNotFound-OldEmpty'].ExpectedExitCode
            $result.LogCheck | Should -BeTrue
            $result.ErrorReportCheck | Should -BeTrue
            $result.WhatIfCheck | Should -BeTrue
        }

        # Show-ErrorPopup がブロッキングなため、CI向け自動実行ではスキップ
        It 'Error-GeneralError-InvalidYaml' -Skip {
            $result = Invoke-DecompileCase -Case $script:Cases['Error-GeneralError-InvalidYaml']
            $result.TimedOut | Should -BeFalse
            $result.ExitCode | Should -Be $script:Cases['Error-GeneralError-InvalidYaml'].ExpectedExitCode
            $result.LogCheck | Should -BeTrue
            $result.ErrorReportCheck | Should -BeTrue
            $result.WhatIfCheck | Should -BeTrue
        }
    }
}
